export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  date: string;
  image?: string;
  body: string[];
};

export const postsA: BlogPost[] = [
  {
    slug: "you-dont-need-more-fans",
    title: "You Don't Need More Fans. You Need to Know Which Fans Would Show Up.",
    description: "More followers don't automatically mean more music revenue. Learn how independent artists can identify real fan demand, find their strongest cities and turn listeners into ticket buyers.",
    keywords: ["independent artist fan growth", "music audience demand", "concert demand independent artist", "fans who would show up", "music monetization"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "Most independent artists think their biggest problem is audience size.",
      "It usually isn't.",
      "The harder problem is knowing which people in that audience actually have intent.",
      "An artist can have thousands of followers and still have no idea where their next 20 ticket buyers will come from.",
      "That's because followers, listeners and buyers are three different things.",
      `IMG:https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Followers aren't demand",
      "A follower has expressed interest.",
      "That's useful.",
      "But it doesn't mean they're going to buy your next release, attend your show or support your next project.",
      "The same applies to streaming.",
      "Spotify can tell you that people listened.",
      "Instagram can tell you that people watched.",
      "Neither necessarily tells you:",
      "\"these are the people who would show up.\"",
      "That's the information independent artists need.",
      "## Start measuring intent",
      "Instead of asking only:",
      "How many followers do I have?",
      "How many streams did I get?",
      "How many views did the video receive?",
      "start asking:",
      "Which cities have the strongest audience?",
      "Which fans engage repeatedly?",
      "Which fans would attend an event?",
      "Which songs create the strongest response?",
      "Where is demand concentrated?",
      "What action should happen next?",
      "Those questions turn an audience into something you can actually operate.",
      "## Why city matters",
      "An independent artist might live in Lagos but have stronger demand in Accra.",
      "Another might have listeners spread across London, Abuja and Nairobi.",
      "Without understanding that distribution, an artist can spend months promoting themselves in the wrong market.",
      "The biggest audience isn't always the best market.",
      "The better question is:",
      "\"where is the strongest actionable demand?\"",
      `IMG:https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## 20 buyers can teach you more than 20,000 views",
      "Imagine two artists.",
      "Artist A receives 20,000 views on a video.",
      "Artist B gets 20 people to buy tickets to a small listening room.",
      "Artist A has more attention.",
      "Artist B has stronger evidence of demand.",
      "That doesn't mean views are worthless.",
      "It means they're upstream.",
      "The career gets interesting when attention becomes action.",
      "## Build from demand",
      "The independent artist doesn't necessarily need another content calendar.",
      "They need a system that can connect the signals:",
      "audience → city → intent → opportunity → action",
      "That's the problem Omniv is built around.",
      "Instead of asking an artist to guess what they should do next, Omniv analyzes their career signals and ranks the highest-impact move.",
      "Sometimes that move is content.",
      "Sometimes it's a release.",
      "Sometimes it's a city.",
      "Sometimes it's a room.",
      "The point is that the answer shouldn't be predetermined.",
      "It should come from the data.",
      `IMG:https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## The real question",
      "You don't need to know whether you have \"enough\" fans.",
      "You need to know:",
      "who would show up?",
      "Because once you know that, you can build around something real.",
      "Find the city.",
      "Open the room.",
      "Own the relationship.",
      "Get paid.",
      "Then do it again.",
      "Start with the free Omniv Artist Scan and find out what your audience is actually telling you.",
    ],
  },
  {
    slug: "how-to-find-your-best-fan-city",
    title: "How to Find Your Best Fan City as an Independent Artist",
    description: "Your strongest demand might be hundreds of miles away. Learn how to identify the cities where your fans are most likely to show up.",
    keywords: ["best fan city independent artist", "music audience by city", "where to play live", "fan mapping artists"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1477959858617-67f85b3a1c2c?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "Most artists know where they live.",
      "Far fewer know where their audience actually is.",
      "And even fewer know which city has the strongest demand for them.",
      "That's a problem.",
      "Because if you're trying to build an independent music career, geography matters.",
      "You can spend six months promoting yourself in the city you're based in while the people most likely to support your career are somewhere else.",
      "Your audience doesn't care where you live.",
      "They care about your music.",
      `IMG:https://images.unsplash.com/photo-1477959858617-67f85b3a1c2c?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Your biggest city isn't always your best city",
      "Let's say your music has listeners in four cities.",
      "Lagos: 8,000 listeners.",
      "Accra: 3,000.",
      "London: 2,000.",
      "Abuja: 1,500.",
      "At first glance, Lagos looks like the obvious market.",
      "But what if the numbers underneath look different?",
      "Lagos has 8,000 listeners but very little direct engagement.",
      "Accra has 3,000 listeners and hundreds of people repeatedly interacting with your music.",
      "London has 2,000 listeners but almost nobody responds to your event announcements.",
      "Abuja has 1,500 listeners and a high percentage of people willing to attend a show.",
      "Suddenly, the biggest audience isn't necessarily the strongest opportunity.",
      "Audience size tells you how many people are there. Demand tells you what those people might do.",
      "## Start with your streaming data",
      "Your streaming platforms can give you useful geographic information.",
      "Look at:",
      "top listener cities",
      "monthly listeners by market",
      "streams by location",
      "repeat listening",
      "playlist activity",
      "audience growth by city",
      "Don't treat these numbers as the answer.",
      "Treat them as clues.",
      "A city with a large listener base deserves investigation.",
      "It doesn't automatically deserve your money.",
      "## Look for stronger signals",
      "The next layer is behavior.",
      "Which cities are producing people who actually interact with you?",
      "Look at:",
      "comments",
      "direct messages",
      "saves",
      "shares",
      "repeat engagement",
      "fan signups",
      "event interest",
      "ticket purchases",
      "merchandise purchases",
      "responses to city-specific announcements",
      "These signals tell you much more than raw reach.",
      "Someone who listens once is useful data.",
      "Someone who says, \"come to Abuja\" is a stronger signal.",
      "Someone who gives you their details and says they'd attend your next event is stronger again.",
      "Someone who buys the ticket has answered the question.",
      "## Build a simple city score",
      "You don't need a complicated analytics department.",
      "Start by looking at four things:",
      "Audience — How many people are listening?",
      "Engagement — How strongly are they responding?",
      "Intent — Are people telling you they want something from you?",
      "Action — Are they actually buying, attending or joining?",
      "The best city is often the one where these signals overlap.",
      "That's your opportunity.",
      "## Don't tour your biggest audience. Follow your strongest demand.",
      "This changes how you think about shows.",
      "Instead of saying: \"I'm based in Lagos, so I'll play Lagos.\"",
      "You can ask: \"Where are the people most likely to show up?\"",
      "That might still be Lagos.",
      "But it might not be.",
      "Maybe your audience has been quietly building in Accra.",
      "Maybe your strongest demand is in Abuja.",
      "Maybe a smaller city has an unusually concentrated fan base.",
      "You won't know until you look.",
      `IMG:https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Your first room doesn't need to be huge",
      "You don't need thousands of people to validate a city.",
      "You need enough people to make the experiment worthwhile.",
      "Twenty committed fans can teach you more than thousands of passive impressions.",
      "If 20 people are willing to buy a ticket, you've learned something.",
      "If 50 show up, you've learned more.",
      "If those people come back for your next event, you've found something much more valuable:",
      "repeatable demand.",
      "That's the foundation of a real market.",
      "## Don't confuse proximity with opportunity",
      "One of the biggest mistakes independent artists make is building around convenience.",
      "You live somewhere.",
      "Your friends are there.",
      "The venues are there.",
      "So you keep trying to make that market work.",
      "But your career doesn't have to follow your current location.",
      "The internet has already made your audience global.",
      "Your job is to figure out where that global audience is becoming concentrated enough to matter.",
      "## Omniv helps artists see the map",
      "This is one of the problems Omniv is designed to solve.",
      "Instead of forcing artists to manually piece together audience information from different platforms, Omniv turns those signals into a clearer picture of where opportunity may exist.",
      "The goal isn't simply: \"Here are your top cities.\"",
      "It's: \"Here's where the evidence suggests you should pay attention next.\"",
      "Because knowing your biggest city is useful.",
      "Knowing your highest-potential city is much more useful.",
      "## Find the city before you spend the money",
      "Before you book the venue.",
      "Before you run the ads.",
      "Before you travel.",
      "Before you announce the tour.",
      "Find the demand.",
      "Know the people.",
      "Test the room.",
      "Then move.",
      "Your next city shouldn't be a guess.",
      "It should be a decision.",
      "Start with the free Omniv Artist Scan and find out what your audience is telling you.",
    ],
  },
  {
    slug: "how-many-fans-to-sell-out-a-show",
    title: "How Many Fans Do You Need to Sell Out a Show?",
    description: "You don't need a million fans. You need the right number of committed fans in the right city. Here's the math.",
    keywords: ["how many fans to sell out a show", "ticket sales independent artist", "small venue capacity", "concert demand"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "You don't need 10,000 fans to sell out a show.",
      "You might not even need 1,000.",
      "The number that matters is much smaller:",
      "how many people are actually willing to show up?",
      "That's a different question from how many people follow you.",
      "And it's one every independent artist should understand before booking a venue.",
      `IMG:https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Followers don't fill rooms",
      "Imagine you have 5,000 Instagram followers.",
      "You announce a small show.",
      "How many tickets do you expect to sell?",
      "If your answer is \"I have no idea,\" you're not alone.",
      "Most artists don't know.",
      "They assume that audience size should translate directly into ticket sales.",
      "It doesn't.",
      "Your followers include:",
      "people who followed you years ago",
      "inactive accounts",
      "other artists",
      "casual listeners",
      "people in other countries",
      "people who like your content but don't listen to your music",
      "people who love the music but aren't ready to attend a show",
      "Your follower count is therefore a terrible way to estimate attendance.",
      "## So how many fans do you actually need?",
      "There's no universal number.",
      "It depends on:",
      "your city",
      "your audience concentration",
      "your relationship with fans",
      "your ticket price",
      "your venue",
      "the type of event",
      "your promotion",
      "how much demand already exists",
      "But the principle is simple:",
      "you need enough committed demand to fill the room you're opening.",
      "If you can identify 30 people who are highly likely to attend, a 30-person room may be a better first move than trying to fill a 300-person venue.",
      "## Start smaller than your ego wants",
      "This is where many artists make an expensive mistake.",
      "They book the venue they want to be seen in rather than the room their audience can currently support.",
      "Then they spend the next month trying to manufacture demand.",
      "The venue is too large.",
      "The advertising bill gets bigger.",
      "The room looks empty.",
      "The artist feels like the event failed.",
      "But the problem wasn't necessarily the music.",
      "The room was wrong.",
      "A smaller room can create the opposite experience.",
      "Thirty people in a room built for thirty feels full.",
      "The audience feels close to the artist.",
      "The artist gets direct feedback.",
      "The economics are easier to understand.",
      "And most importantly:",
      "you've created evidence.",
      "## Think in conversion rates",
      "Suppose you have 2,000 followers.",
      "If only 1% of those followers are genuinely ready to attend, that's 20 people.",
      "That's not nothing.",
      "That's a room.",
      "Now imagine you improve the quality of your audience relationship and 3% are willing to attend.",
      "That's 60 people.",
      "You didn't need to suddenly acquire 4,000 new followers.",
      "You increased the amount of existing attention that became action.",
      "That's why demand matters more than vanity metrics.",
      "## Your first show is also a test",
      "A small show shouldn't only be viewed as a revenue event.",
      "It's market research.",
      "You learn:",
      "who actually comes",
      "where they traveled from",
      "what they paid",
      "which song gets the biggest reaction",
      "what they bought",
      "what they want next",
      "whether they'd come again",
      "That information can change your entire strategy.",
      "The first room tells you what the second room should look like.",
      "## The real metric is repeat demand",
      "One sold-out event is exciting.",
      "Two is interesting.",
      "Three starts becoming a pattern.",
      "If the same people continue showing up, bringing friends, buying tickets and responding to your announcements, you've built something much more valuable than a large follower count.",
      "You've built repeatable demand.",
      "That's what independent artists should be chasing.",
      "## Don't ask how many fans you need",
      "Ask:",
      "how many people do I know would come?",
      "Then build the room around that number.",
      "If you know 20 people will come, open a 20–30 person room.",
      "If you know 80 will come, open a larger room.",
      "If you don't know, don't guess.",
      "Find out.",
      `IMG:https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Omniv helps turn audience signals into decisions",
      "Omniv is designed to help independent artists understand their audience, identify demand and determine which opportunities deserve attention.",
      "Instead of looking at your follower count and guessing what it means, the goal is to understand the signals underneath it.",
      "Who is engaged?",
      "Where are they?",
      "What are they responding to?",
      "What might they actually do?",
      "Then you can make a better decision about your next move.",
      "Because the objective isn't to look popular.",
      "It's to build something that works.",
      "## Your first room can be smaller than you think",
      "You don't need a stadium.",
      "You need a room you can fill.",
      "Twenty people who paid to see you are not \"only 20 fans.\"",
      "They're evidence that something is working.",
      "Take those 20.",
      "Learn from them.",
      "Find 20 more.",
      "Open the next room.",
      "Then repeat.",
      "The goal isn't the biggest room.",
      "It's the room you can fill again.",
      "Start with the free Omniv Artist Scan and find out where your strongest audience signals are.",
    ],
  },
];
