import type { BlogPost } from "./posts-data-a";

export const postsB: BlogPost[] = [
  {
    slug: "how-to-host-your-first-listening-party",
    title: "How to Host Your First Listening Party as an Independent Artist",
    description: "Small rooms build real careers. A step-by-step guide to planning, promoting, and profiting from your first ticketed listening session.",
    keywords: ["listening party independent artist", "ticketed listening session", "how to host listening party", "small music events"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "You don't need a club.",
      "You don't need a major sponsor.",
      "You don't need thousands of followers.",
      "You need a room, a reason to bring people together, and enough demand to make the room worth opening.",
      "That's what makes a listening party one of the most interesting opportunities for an independent artist.",
      "It turns passive attention into a real-world experience.",
      "And it gives you something social media can't:",
      "proof that people will actually show up.",
      `IMG:https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## What is a listening party?",
      "A listening party is a small event where fans gather to hear your music in a more intimate setting.",
      "It can happen before a release, around a new project, or simply as a standalone experience for your biggest supporters.",
      "It doesn't have to look like a traditional concert.",
      "That's the point.",
      "You can create something smaller, more personal and easier to fill.",
      "The experience might include:",
      "listening to unreleased music",
      "telling the stories behind songs",
      "performing a few tracks",
      "answering questions",
      "meeting fans",
      "selling merchandise",
      "collecting fan information",
      "taking photos and creating content",
      "The goal isn't just to play music.",
      "It's to create a reason for your most interested fans to be in the same room.",
      "## Start with the demand, not the venue",
      "Don't begin by searching for the biggest venue you can afford.",
      "Start by asking:",
      "who would actually come?",
      "Look through your audience.",
      "Identify people who are consistently engaging with your music.",
      "Pay attention to people who respond to announcements.",
      "Ask your audience directly.",
      "Collect city information.",
      "Give people a simple way to express interest.",
      "If 15 people say they'd attend, that's useful.",
      "If 50 say they'd attend, that's much stronger.",
      "Now you have something to work with.",
      "## Choose a room you can fill",
      "Your first listening party should feel full.",
      "A room with 25 people can feel electric.",
      "A room designed for 200 people with 25 people inside feels empty.",
      "Don't optimize for prestige.",
      "Optimize for experience.",
      "Look for:",
      "small creative spaces",
      "studios",
      "cafes",
      "galleries",
      "private event spaces",
      "intimate venues",
      "community spaces",
      "The best room is the one that fits your actual demand.",
      "## Set a simple ticket price",
      "Your first event doesn't have to maximize revenue.",
      "It needs to validate willingness to pay.",
      "A modest ticket price can filter casual interest from real intent.",
      "Someone saying \"I'd love to come\" is nice.",
      "Someone actually buying a ticket is information.",
      "Your price should cover the economics of the event while remaining appropriate for your audience and location.",
      "Track what happens.",
      "If people buy quickly, you've learned something.",
      "If nobody converts, you've learned something too.",
      "## Give people a reason to attend",
      "Don't sell the event as \"come hear me play.\"",
      "Give them something they can't get from a stream.",
      "Maybe they're hearing an unreleased project first.",
      "Maybe you're telling the stories behind the songs.",
      "Maybe you're performing stripped-down versions.",
      "Maybe there's a private Q&A.",
      "Maybe they receive something exclusive.",
      "The experience should answer:",
      "why should I leave my house for this?",
      "## Build the room before the event",
      "Don't rely entirely on a single Instagram post.",
      "Talk to the people who already care.",
      "Use your fan list.",
      "Use direct communication.",
      "Talk about the experience.",
      "Show preparation.",
      "Share small pieces of what people will get.",
      "Make the event feel like something they're joining rather than another promotional announcement.",
      "## Capture the right information",
      "The event isn't over when everyone leaves.",
      "You now know something about those people.",
      "Where are they from?",
      "What brought them there?",
      "What did they like?",
      "Would they come again?",
      "Would they attend another city?",
      "What would they pay for next?",
      "With permission, collect useful contact information so you can communicate with them directly.",
      "A room should create more than ticket revenue.",
      "It should create relationship equity.",
      "## Turn one room into the next move",
      "After the event, look at what happened.",
      "Maybe 30 people came.",
      "Maybe 25 bought tickets.",
      "Maybe 12 bought merchandise.",
      "Maybe several people asked when the next event would happen.",
      "Maybe most attendees came from one part of the city.",
      "Maybe people traveled from another city entirely.",
      "Those are signals.",
      "Use them.",
      "The next room should be smarter because the first one happened.",
      `IMG:https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## This is where Omniv fits",
      "Omniv is built to help artists understand the demand around their career and decide what deserves attention next.",
      "That can include identifying strong audience cities, understanding fan intent and turning those signals into actionable opportunities.",
      "The point isn't to tell every artist: \"host a listening party.\"",
      "The point is to help answer: \"is a room the right move for you right now?\"",
      "And if it is: where, for whom, and what should happen next?",
      "That's a much better question.",
      "## Your first room doesn't need to be impressive",
      "It needs to be real.",
      "A small room filled with people who genuinely want to be there can teach you more about your career than another month of watching your follower count move.",
      "Don't wait until you're famous.",
      "Find the people who care now.",
      "Give them somewhere to show up.",
      "Then build from there.",
      "Own the relationship. Open the room. Get paid.",
      "Start with the free Omniv Artist Scan to see what your audience signals suggest you should do next.",
    ],
  },
  {
    slug: "how-to-build-an-owned-fanbase",
    title: "How to Build an Owned Fanbase as an Independent Artist",
    description: "Social media can disappear overnight. Your email list and fan database can't. Here's how to build an audience you control.",
    keywords: ["owned fanbase independent artist", "email list for musicians", "fan database", "owned audience music"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "Social media can help you build an audience.",
      "But it shouldn't be the only place your audience exists.",
      "Because you don't own Instagram.",
      "You don't own TikTok.",
      "You don't control YouTube's recommendation system.",
      "And you don't control what happens to your reach tomorrow.",
      "What you can own is the relationship with the people who choose to hear from you directly.",
      "That's what an owned audience means.",
      `IMG:https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## What is an owned audience?",
      "An owned audience is a group of fans you can communicate with directly, with their permission, without relying entirely on an algorithm to reach them.",
      "That might include:",
      "email addresses",
      "phone numbers",
      "WhatsApp contacts",
      "fan profiles",
      "city information",
      "event attendance",
      "purchase history",
      "expressed interests",
      "The important part isn't simply collecting contact information.",
      "It's understanding the people behind it.",
      "A list of 2,000 random emails isn't necessarily valuable.",
      "A list of 200 genuine fans who regularly listen, attend events and want to hear from you can be extremely valuable.",
      "## Your followers are rented attention",
      "Imagine you build an Instagram following of 20,000 people.",
      "Then the platform changes how it distributes your content.",
      "Your next post reaches 600 people.",
      "Your audience didn't disappear.",
      "Your access to them changed.",
      "That's the fundamental problem with building your entire career on rented distribution.",
      "You can have millions of followers and still struggle to reach the people who matter.",
      "An owned audience gives you another layer of control.",
      "If someone gives you their email or joins your fan community, you have a direct way to communicate with them.",
      "That's powerful.",
      "## Start collecting more than an email",
      "An email address is useful.",
      "But context makes it much more useful.",
      "For an artist, some of the most valuable information can be simple:",
      "Who are they?",
      "Where are they?",
      "What do they like?",
      "Would they attend a show?",
      "Have they bought anything?",
      "When did they last interact with you?",
      "Imagine having 500 fans in your database.",
      "Now imagine knowing:",
      "180 are in Lagos",
      "90 are in Accra",
      "40 are in Abuja",
      "25 are in London",
      "70 have attended an event",
      "120 said they'd attend another",
      "60 purchased something from you",
      "That's no longer just a fan list.",
      "That's the beginning of a business intelligence layer for your career.",
      "## Give fans a reason to join",
      "Don't ask people for their information for no reason.",
      "Give them something worth joining for.",
      "That could be:",
      "early access to music",
      "unreleased tracks",
      "private listening sessions",
      "ticket presales",
      "exclusive events",
      "behind-the-scenes content",
      "merchandise access",
      "direct updates",
      "fan-only experiences",
      "The relationship should feel like an exchange.",
      "You're giving them access.",
      "They're giving you permission to communicate directly.",
      "## Your biggest fans aren't necessarily your biggest followers",
      "Your most valuable fans might not be the people commenting under every post.",
      "They might be the person who quietly buys every ticket.",
      "The person who brings three friends.",
      "The person who joins every listening party.",
      "The person who tells everyone about your new song.",
      "The person who asks when you're coming to their city.",
      "That's why audience size isn't enough.",
      "You need to understand fan behavior.",
      "## Turn your audience into a map",
      "Once you know where your fans are, you can make better decisions.",
      "Maybe you're planning your next event.",
      "Instead of guessing where to go, look at your audience.",
      "Maybe you discover that one city has a surprisingly concentrated group of people who have already expressed interest in seeing you.",
      "That's actionable.",
      "You can test that market.",
      "Open a small room.",
      "See who actually comes.",
      "Then learn from the result.",
      "## Don't build your entire career on a feed",
      "Your social profiles are valuable.",
      "Use them.",
      "Grow them.",
      "Publish consistently.",
      "But don't let the platform become the entire business.",
      "Use social media to discover and attract people.",
      "Then give the people who genuinely care a way to build a deeper relationship with you.",
      "That's the difference between having followers and building an audience you can operate.",
      `IMG:https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Omniv helps artists build the layer underneath the feed",
      "Omniv is designed around turning audience activity into something an independent artist can actually use.",
      "Fan information, city demand, engagement and other signals can become part of a clearer picture of the career.",
      "The objective isn't to replace social media.",
      "It's to stop depending on it for everything.",
      "Because the strongest independent artists won't just have audiences.",
      "They'll know their audiences.",
      "They'll know where they are.",
      "They'll know what they want.",
      "And they'll know what to do with that information.",
      "Don't just collect followers. Build relationships you can reach.",
      "Start with the free Omniv Artist Scan and see what your audience signals reveal.",
    ],
  },
];
