export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  date: string;
  image?: string;
  body: string[];
};

export const posts: BlogPost[] = [
  {
    slug: "you-dont-need-more-fans",
    title: "You Don't Need More Fans. You Need to Know Which Fans Would Show Up.",
    description: "More followers don't automatically mean more music revenue. Learn how independent artists can identify real fan demand, find their strongest cities and turn listeners into ticket buyers.",
    keywords: ["independent artist fan growth", "music audience demand", "fans who would show up"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "Most independent artists think their biggest problem is audience size.",
      "It usually isn't.",
      "The harder problem is knowing which people in that audience actually have intent.",
      "An artist can have thousands of followers and still have no idea where their next 20 ticket buyers will come from.",
      "That's because followers, listeners and buyers are three different things.",
      `IMG:https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Followers aren't demand",
      "A follower has expressed interest. That's useful. But it doesn't mean they're going to buy your next release or attend your show.",
      "Spotify can tell you that people listened. Instagram can tell you that people watched. Neither necessarily tells you who would show up.",
      "## Start measuring intent",
      "Instead of only asking how many followers or streams you have, ask: which cities are strongest, who would attend, where is demand concentrated, what action should happen next?",
      "## Why city matters",
      "You might live in Lagos but have stronger demand in Accra. The biggest audience isn't always the best market.",
      `IMG:https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## 20 buyers can teach you more than 20,000 views",
      "Artist A gets 20,000 views. Artist B gets 20 ticket buyers. Artist B has stronger evidence of demand. Views are upstream. The career gets interesting when attention becomes action.",
      "## Build from demand",
      "Connect the signals: audience → city → intent → opportunity → action. That's what Omniv is built around — ranked moves from your data, not random tips.",
      "## The real question",
      "who would show up?",
      "Find the city.",
      "Open the room.",
      "Own the relationship.",
      "Get paid.",
      "Then do it again.",
      "Start with the free Omniv Artist Scan and find out what your audience is actually telling you.",
    ],
  },
  {
    slug: "how-to-find-your-best-fan-city",
    title: "How to Find Your Best Fan City as an Independent Artist",
    description: "Your strongest demand might be hundreds of miles away. Learn how to identify the cities where your fans are most likely to show up.",
    keywords: ["best fan city independent artist", "music audience by city", "fan mapping artists"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1477959858617-67f85b3a1c2c?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "Most artists know where they live. Far fewer know where their audience actually is. And even fewer know which city has the strongest demand for them.",
      "That's a problem. Geography matters. Your audience doesn't care where you live. They care about your music.",
      `IMG:https://images.unsplash.com/photo-1477959858617-67f85b3a1c2c?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Your biggest city isn't always your best city",
      "Lagos might have 8,000 listeners with little engagement. Accra might have 3,000 with hundreds interacting. Abuja might have 1,500 with high intent to attend. Suddenly the biggest audience isn't the strongest opportunity.",
      "Audience size tells you how many people are there. Demand tells you what those people might do.",
      "## Start with your streaming data",
      "Look at top listener cities, streams by location, repeat listening, and growth by city. Treat numbers as clues, not answers.",
      "## Look for stronger signals",
      "Comments, DMs, saves, fan signups, event interest, ticket purchases. Someone who says come to Abuja is stronger than a passive stream. Someone who buys a ticket has answered the question.",
      "## Build a simple city score",
      "Audience. Engagement. Intent. Action. The best city is where these overlap.",
      "## Don't tour your biggest audience. Follow your strongest demand.",
      "Ask: where are the people most likely to show up? That might still be home. It might not be.",
      `IMG:https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Your first room doesn't need to be huge",
      "Twenty committed fans can teach you more than thousands of passive impressions. Repeatable demand is the foundation of a real market.",
      "## Don't confuse proximity with opportunity",
      "Building around convenience is a trap. The internet made your audience global. Your job is to find where it concentrates enough to matter.",
      "## Omniv helps artists see the map",
      "Omniv turns signals into a clearer picture of where to pay attention next. Knowing your highest-potential city is more useful than knowing your biggest city.",
      "## Find the city before you spend the money",
      "Before the venue, the ads, the travel, the tour — find the demand. Your next city shouldn't be a guess. It should be a decision.",
      "Start with the free Omniv Artist Scan and find out what your audience is telling you.",
    ],
  },
  {
    slug: "how-many-fans-to-sell-out-a-show",
    title: "How Many Fans Do You Need to Sell Out a Show?",
    description: "You don't need a million fans. You need the right number of committed fans in the right city. Here's the math.",
    keywords: ["how many fans to sell out a show", "ticket sales independent artist", "small venue capacity"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "You don't need 10,000 fans to sell out a show. You might not even need 1,000.",
      "The number that matters is: how many people are actually willing to show up?",
      `IMG:https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Followers don't fill rooms",
      "5,000 Instagram followers doesn't answer how many tickets you'll sell. Followers include inactive accounts, other artists, casual listeners, and people in other countries. Follower count is a terrible attendance estimator.",
      "## So how many fans do you actually need?",
      "There's no universal number. It depends on city, concentration, relationship, price, venue, and existing demand. The principle: enough committed demand to fill the room you're opening.",
      "## Start smaller than your ego wants",
      "Booking the prestige venue before the audience can fill it is expensive. Thirty people in a 30-person room feels full. Twenty-five in a 200-person room feels empty. The room was wrong — not necessarily the music.",
      "## Think in conversion rates",
      "2,000 followers at 1% ready to attend is 20 people — a room. Improve the relationship to 3% and you have 60 without acquiring 4,000 new followers. Demand matters more than vanity metrics.",
      "## Your first show is also a test",
      "Learn who comes, from where, what they paid, what they want next. The first room tells you what the second should look like.",
      "## The real metric is repeat demand",
      "One sold-out event is exciting. Three starts a pattern. Repeatable demand is what independents should chase.",
      "## Don't ask how many fans you need",
      "Ask: how many people do I know would come?",
      "Then build the room around that number.",
      "## Omniv helps turn audience signals into decisions",
      "Understand who is engaged, where they are, what they might do — then decide the next move. The objective isn't to look popular. It's to build something that works.",
      "Twenty people who paid are evidence. Take those 20. Learn. Find 20 more. Open the next room.",
      "Start with the free Omniv Artist Scan and find out where your strongest audience signals are.",
    ],
  },
  {
    slug: "how-to-host-your-first-listening-party",
    title: "How to Host Your First Listening Party as an Independent Artist",
    description: "Small rooms build real careers. A step-by-step guide to planning, promoting, and profiting from your first ticketed listening session.",
    keywords: ["listening party independent artist", "ticketed listening session", "small music events"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "You don't need a club, a major sponsor, or thousands of followers. You need a room, a reason, and enough demand to make the room worth opening.",
      "A listening party turns passive attention into proof that people will show up.",
      `IMG:https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## What is a listening party?",
      "A small event where fans hear your music in an intimate setting — unreleased tracks, stories, a few performances, Q&A, merch, fan capture. Not a traditional concert. Easier to fill.",
      "## Start with the demand, not the venue",
      "Ask: who would actually come? Collect city and interest. Fifteen yeses is useful. Fifty is stronger.",
      "## Choose a room you can fill",
      "Twenty-five people in a fitting room feels electric. Twenty-five in a 200-cap room feels empty. Optimize for experience, not prestige.",
      "## Set a simple ticket price",
      "Validate willingness to pay. A ticket is information. I'd love to come is not the same as buying.",
      "## Give people a reason to attend",
      "Something they can't get from a stream: unreleased music, stories, stripped-down sets, exclusive access.",
      "## Build the room before the event",
      "Use your fan list and direct communication. Make it feel like joining, not another promo post.",
      "## Capture the right information",
      "Where are they from? Would they come again? What would they pay next? A room should create relationship equity, not only ticket revenue.",
      "## Turn one room into the next move",
      "Signals from the first night make the second room smarter.",
      "## This is where Omniv fits",
      "Omniv helps answer whether a room is the right move — and where, for whom, what next.",
      "Own the relationship. Open the room. Get paid.",
      "Start with the free Omniv Artist Scan to see what your audience signals suggest next.",
    ],
  },
  {
    slug: "how-to-build-an-owned-fanbase",
    title: "How to Build an Owned Fanbase as an Independent Artist",
    description: "Social media can disappear overnight. Your email list and fan database can't. Here's how to build an audience you control.",
    keywords: ["owned fanbase independent artist", "email list for musicians", "owned audience music"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "Social media helps you build an audience — but it shouldn't be the only place it exists. You don't own Instagram, TikTok, or the algorithm. You can own the relationship with people who choose to hear from you directly.",
      `IMG:https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## What is an owned audience?",
      "Fans you can reach with permission: email, phone, city, attendance, purchases, interests. Context makes a list valuable — 200 genuine fans beat 2,000 random emails.",
      "## Your followers are rented attention",
      "Platforms change distribution. Your next post reaches a fraction. The audience didn't disappear — your access did. Owned channels give you another layer of control.",
      "## Start collecting more than an email",
      "Who, where, what they like, would they attend, last interaction. City counts and intent turn a list into business intelligence.",
      "## Give fans a reason to join",
      "Early access, unreleased tracks, presales, exclusive sessions — an exchange, not a form.",
      "## Your biggest fans aren't necessarily your biggest followers",
      "The quiet ticket buyer, the friend-bringer, the person asking when you're in their city — behavior matters more than comment volume.",
      "## Turn your audience into a map",
      "Know where demand concentrates. Test that market. Open a small room. Learn.",
      "## Don't build your entire career on a feed",
      "Use social to attract. Give people who care a deeper relationship. That's the difference between followers and an audience you can operate.",
      "## Omniv helps artists build the layer underneath the feed",
      "Fan information, city demand, and signals become a clearer career picture. Stop depending on platforms for everything.",
      "Don't just collect followers. Build relationships you can reach.",
      "Start with the free Omniv Artist Scan and see what your audience signals reveal.",
    ],
  },
  {
    slug: "ai-tools-for-musicians-what-ai-should-do",
    title: "AI Tools for Musicians: What AI Should Actually Do for Independent Artists",
    description: "Most AI tools give artists more work. The useful ones rank the next move. Here's how Ziki and real career AI should think.",
    keywords: ["AI tools for musicians", "AI music manager", "Ziki Omniv", "AI career strategist artists"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "AI can write lyrics, generate art, make captions — and add 50 more items to your to-do list. That's the problem. Artists don't need more tasks. They need better decisions.",
      `IMG:https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## The AI music tools problem",
      "Most tools ask: what can I create for you? Useful — but many artists already have too many options. The real problem is choosing.",
      "## AI should reduce decisions, not create more",
      "Five possible moves. Generic advice says do all five. A strategic system asks which has the highest expected impact right now.",
      "## Generic advice isn't strategy",
      "How do I promote my song yields 20 tactics. Context changes the answer: city demand, release strength, live interest, content fatigue.",
      "## Your AI needs to understand your career",
      "Not what works for musicians — what is most likely to work for me right now — catalogue, audience, cities, goals, constraints.",
      "## AI can become a strategic layer",
      "System A lists 20 marketing ideas. System B says: strong demand in Accra, test a 30-person room — don't release another song this week. That's a decision.",
      "## This is the idea behind Ziki",
      "Ziki isn't another chatbot for generic advice. It's a strategic layer: what matters, what's emerging, what next, and what not to waste time on.",
      "## The best AI recommendation might be don't",
      "Don't release yet. Don't spend on ads yet. One high-impact action over five busy ones.",
      "## The future isn't more content",
      "Content is cheap. Good decisions are scarce. Winners know what deserves to be produced.",
      "## Omniv is built around that idea",
      "Ranked opportunities from your signals — not another checklist. Career strategist, not content spam.",
      "Your career doesn't need another chatbot. It needs better decisions.",
      "Start with the free Omniv Artist Scan and see what your data says your next move should be.",
    ],
  },
  {
    slug: "make-money-without-only-streaming",
    title: "How Independent Artists Can Make Money Without Relying Only on Streaming",
    description: "Streams are not the only way. Rooms, tips, lists, and direct experiences turn attention into real revenue.",
    keywords: ["make money independent artist", "music revenue beyond streaming", "ticketed rooms", "artist tips"],
    date: "2026-08-18",
    image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=1200&h=675&q=80",
    body: [
      "Streaming matters. It shouldn't be the only way you think about money. A stream is not a customer. An audience is not a business.",
      `IMG:https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=1200&h=675&q=80`,
      "## Streaming is only one part of the picture",
      "Tickets, listening parties, merch, memberships, tips, licensing, sync, brand partnerships, direct experiences — not every artist needs all of them. You don't need one source only.",
      "## Your audience already has economic value",
      "A weekly listener who buys a ticket, brings friends, buys a shirt, and joins your list is worth far more than one stream.",
      "## Start with a room",
      "20 fans at $10 is $200 — plus merch, tips, and permission to stay in touch. Money matters. Information matters more.",
      "## Don't underestimate small transactions",
      "Ten people at $10 is $100. Fifty is $500. One hundred is $1,000. Engaged audiences make the numbers interesting.",
      "## Tickets are more than revenue",
      "Buying a ticket is commitment. Live shows reveal who is willing to act — something streaming can't fully show.",
      "## Your fan list makes monetization easier",
      "Direct reach when something meaningful happens. Context — city, past attendance, interest — turns a list into infrastructure.",
      "## Don't monetize everything",
      "Value first: music, experiences, community. Then invite support. Constant BUY THIS kills listening.",
      "## Think beyond the stream",
      "Discover → follow → join list → room → ticket → friend → next show. Ask what happened after they listened.",
      "## Omniv connects audience signals to opportunity",
      "Where demand is strongest, who is engaged, whether a room makes sense, what deserves attention next.",
      "Find 20 people. Give them something worth paying for. Learn. Find 20 more. Repeat.",
      "The first $1,000 might be sitting in the audience you already have.",
      "Start with the free Omniv Artist Scan and find out where your strongest audience opportunities are.",
    ],
  },
];

export function getPost(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug);
}

export function allSlugs(): string[] {
  return posts.map((p) => p.slug);
}
